name: wdf_workshop
channels:
    - conda-forge
dependencies:
    - python=3.10
    - jupyterlab>=3
    - notebook
    - rioxarray
    - pandas
    - numpy
    - geopandas
    - rasterio
    - jupyter-server-proxy
    - xarray_leaflet
    - leafmap>=0.11.3
    - localtileserver>=0.4.0
